version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: siraamer/reverseproxy:v1
  backend_user:
    build:
      context: ../../udagram-user
    image: siraamer/user-image:v1
  backend_feed:
    build:
      context: ../../udagram-feed
    image: siraamer/feed-image:v1
  frontend:
    build:
      context: ../../udagram-frontend
    image: siraamer/frontend-image:v1
